### ISSUE TITLE
UI/UX Design sub-page considerations

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#261]
Creating an issue to track a few of the design issues we have open for the team (especially @austinhernandez and @bpdesigns) to be aware of as the subpages are designed. Some are pending more feedback, but these are things we have talked about and prioritized with Brooklyn to consider for MVP:

- [x] Integrated content UI/UX design (#218) - details page, results page, filter section & throughout the site
- [x] Info content pages (#223) + improving access to info content from top navigation
- [x] Create favicon (#196) - global 
- [ ] Collapsed filter selection visual representation (#267)
- [x] Update footer, if you think it needs updating, to align with the new design (#288)

**Comment by amandacostello** [comment]
Here's the finished headers (h2) and the plain-languaging for the facility codes.

https://docs.google.com/document/d/139lF-VWfXkps0CJJLJ4AzWul0Uiq4jhHGG3pgTMn7lc/edit#
