### ISSUE TITLE
Create meta descriptions and icons for sharing

### ISSUE THREAD

**Issue by allisonnorman** [18F/samhsa-prototype#378]
We need meta descriptions for each of the pages for sharing and social media + icon(s):
- [x] Meta descriptions for each page - @amandacostello (Each content page,  /results (which is also the search page), facility details page)
- [x] Sitewide description for the homepage - @amandacostello 
- [x] Fallback description in case one doesn't exist for the page - @amandacostello 
- [x] Icon - see example below + https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image - @austinhernandez 

Example from PRA in Slack: 
![Screen Shot 2019-09-26 at 1 41 44 PM](https://user-images.githubusercontent.com/6900926/65723518-673dd380-e063-11e9-8692-80a6d4d2572d.png)

**Comment by hursey013** [comment]
I think `Sitewide description for the homepage` and `Fallback description in case one doesn't exist for the page` can likely be the same thing.

**Comment by austinhernandez** [comment]
Here is an example of [Summary Card with Large Image](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image), thoughts?  
![image](https://user-images.githubusercontent.com/23194720/65799211-8b6fe200-e141-11e9-8471-84c2d62ba3af.png)

**Comment by amandacostello** [comment]
All meta tag descriptions are here! https://docs.google.com/spreadsheets/d/1H_e7KDSijBGgms4leESqH_LFMmLnnp3MUX_YbLi2kzA/edit#gid=0

**Comment by austinhernandez** [comment]
Also, I made this smaller icon if it's just going to be text and not the whole Twitter card
![150x150Icon](https://user-images.githubusercontent.com/23194720/66002154-0b16ed00-e471-11e9-9d0c-492456b70948.png)

**Comment by austinhernandez** [comment]
![400x400](https://user-images.githubusercontent.com/23194720/66058630-b1620180-e508-11e9-93c3-4017704dc013.png)

![card](https://user-images.githubusercontent.com/23194720/66059764-909aab80-e50a-11e9-87c7-960d4e6a1c2f.png)
